import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { Button, Container, Flex, HStack, Text } from '@chakra-ui/react'
import { MenuItem } from 'components/molecules/MenuItem/MenuItem'
import Link from 'next/link'
import Hero from 'components/molecules/Hero/Hero'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex w="100%" flexDirection="row" alignContent="center" p="6px 6px">
          <Text fontSize="36px" fontWeight="bold" lineHeight="42px" color="#1F79BA" flexGrow={1}>Todo App</Text>
          <HStack spacing="16px" alignContent="center">
            <MenuItem>
              <Link href="/blog">Blog</Link>
            </MenuItem>
            <MenuItem>
              <Link href="/blog">Product</Link>
            </MenuItem>
            <MenuItem>
              <Link href="/blog">Pricing</Link>
            </MenuItem>
          </HStack>
          <Flex marginLeft="82px">
            <Button>Get Started</Button>
          </Flex>
      </Flex>
      <Flex>
        <Hero />
      </Flex>
    </>
  )
}
